#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

${DIR}/install-node20 &&
${DIR}/update-npm 10 &&
npm install 

echo -e "${SCRIPT}: completed (OK)"
